### ISSUE TITLE
Expose the ajax-service at a lower level

### ISSUE THREAD

**Issue by gdub22** [tildeio/ember-cli-fastboot#10]
`najax` should be directly accessible for apps that want to use basic ajax requests, and then decorated for ember-data specific usage.

**Comment by stefanpenner** [comment]
https://github.com/stefanpenner/ember-fetch ;);)

**Comment by gdub22** [comment]
@stefanpenner nice, although it looks like github's fetch shot down node support?

I now see that najax is exposed as a global in fastboot, so it's not a blocker.
Would still be nice to to expose the promise/runloop wrapper to be more generic.

**Comment by stefanpenner** [comment]
Would be good to add mode support. It's a worthy cause

**Comment by tomdale** [comment]
Our plan here is to have an `ember-cli-ajax` addon that injects an AJAX service that automatically does the right thing in both environments.
