### ISSUE TITLE
Wrong manifest file paths

### ISSUE THREAD

**Issue by jpadilla** [tildeio/ember-cli-fastboot#102]
`fastboot-dist/package.json` looks like this:

```json
{
  "dependencies": {},
  "fastboot": {
    "moduleWhitelist": [],
    "manifest": {
      "appFile": "assets/fastboot-demo.js",
      "htmlFile": "index.html",
      "vendorFile": "assets/vendor.js"
    }
  }
}
```

should have been:

```json
{
  "dependencies": {},
  "fastboot": {
    "moduleWhitelist": [],
    "manifest": {
      "appFile": "assets/fastboot-demo-SHA.js",
      "htmlFile": "index.html",
      "vendorFile": "assets/vendor-SHA.js"
    }
  }
}
```

**Comment by danmcclain** [comment]
@jpadilla I was just about to report this same thing! I have a couple potential fixes in mind. The package.json is written before the fingerprinting happens, so we could make sure that the asset rev addon is aware, but if you use prepended domains, you then have to strip them out. I am going to see if I can spike a solution now

**Comment by danmcclain** [comment]
I have a spike that resolves this locally, but ran into an issue that fastboot choked on minimized js, going to prepare PRs to make asset rev'ing work soon (one here, one to `ember-fastboot-server`)

**Comment by jpadilla** [comment]
@danmcclain Ace! Do let me know if there's something I can do to help out.

**Comment by danmcclain** [comment]
@jpadilla Should be taken care of by https://github.com/ember-fastboot/ember-fastboot-server/pull/11 and #103 (used together) Also, you need to add `'json'` to your `replaceExtensions` so the `fastboot-dist/package.json` is update

**Comment by jpadilla** [comment]
@danmcclain will try to give this a try today, thanks!

**Comment by tomdale** [comment]
This actually ended up being more of a pain in the ass than anticipated because of broccoli-asset-rev but I have a fix coming up.
