### ISSUE TITLE
navigator is not defined

### ISSUE THREAD

**Issue by RuslanZavacky** [tildeio/ember-cli-fastboot#104]
Seems like when trying to start fastboot on a project where addons use 'navigator' will just fail.

```
Built project successfully. Stored in "fastboot-dist".
Installing FastBoot npm dependencies
  ember-cli-fastboot:ember-app app created; app=fastboot-dist/assets/vetoza-ui.js; vendor=fastboot-dist/assets/vendor.js +0ms
navigator is not defined
ReferenceError: navigator is not defined
    at fastboot-dist/assets/vendor.js:73754:33
    at fastboot-dist/assets/vendor.js:73678:20
    at fastboot-dist/assets/vendor.js:73680:2
```

is it worth trying to catch such situation in fastboot, or its better to fix addons straight away?

**Comment by tomdale** [comment]
This should hopefully at least result in better error messages once https://github.com/tildeio/ember-cli-fastboot/pull/78 lands. Either way addons should not try to access `navigator` at evaluation time; so long as access is constrained to `didInsertElement()` they should work after that.

**Comment by rynam0** [comment]
Apologies in advance if this belongs in a new issue but this seemed like the right place to ask this.

I just experienced this in my first attempt at installing fastboot in an existing app. This app uses an addon that imports selectize.js which has 2 references to navigator. 
``
  app.import(app.bowerDirectory + '/selectize/dist/js/standalone/selectize.js');
``
Is there any workaround you can think of for apps that consume addons which bring in third party JS files?

``
Built project successfully. Stored in "fastboot-dist".
Installing FastBoot npm dependencies
navigator is not defined
ReferenceError: navigator is not defined
    at /Users/rynam0/Development/github/robot-db-ui/fastboot-dist/fastboot/bower_components/selectize/dist/js/standalone/selectize.js:711:1
    at /Users/rynam0/Development/github/robot-db-ui/fastboot-dist/fastboot/bower_components/selectize/dist/js/standalone/selectize.js:635:1
    at /Users/rynam0/Development/github/robot-db-ui/fastboot-dist/fastboot/bower_components/selectize/dist/js/standalone/selectize.js:637:1
``
Thanks!

**Comment by tomdale** [comment]
This definitely needs to make it into the docs, but you should be able to guard `app.import` and only call it if `process.env.EMBER_CLI_FASTBOOT` is not set.

**Comment by rynam0** [comment]
Awesome, thanks!

**Comment by simonc** [comment]
Hi @tomdale I'm facing the `navigator is not defined` issue but not sure of what I can do to work around it. I'm a node-noob so I don't really get your last comment.

For instance I'm using [ivy-codemirror](https://github.com/IvyApp/ivy-codemirror) that provides an Ember component for Codemirror. It depends on Codemirror through Bower. When I run `ember fastboot` it explodes with the navigator error coming from Codemirror's code.

So in that situation what is the solution to prevent this error?

Thanks

**Comment by danmcclain** [comment]
@simonc A PR will need to be mad to `ivy-codemirror` to guard the `app.import` calls here that access `navigator`: https://github.com/IvyApp/ivy-codemirror/blob/master/index.js#L13-L35

Here is a PR I made on a different addon to guard the import: https://github.com/brandonhilkert/ember-cli-sticky/pull/11/files

**Comment by simonc** [comment]
@danmcclain Ok, the `app.import` guard is not in my own app, that makes more sense now :grin: thank you very much, I'll PR ivy-codemirror :)
