### ISSUE TITLE
fastboot and ember-data work fine together?

### ISSUE THREAD

**Issue by speed1speed1** [tildeio/ember-cli-fastboot#107]
I used fastboot and ember-data building an example, but always broken on ajax.
Ember-data using "Ember.$.ajax(hash)" to call ajax, but fastboot error on undefined property ajax.
What I miss it?
Najax looks not working.

`TypeError: Cannot read property 'ajax' of undefined`
`    at fastboot-dist/assets/vendor.js:78758:25`
`    at Object.initializePromise (fastboot-dist/assets/vendor.js:63458:7)`
`    at new Promise (fastboot-dist/assets/vendor.js:65308:21)`
`    at exports.default._emberDataAdapter.default.extend.ajax (fastboot-dist/assets/vendor.js:78726:14)`

ember: 2.3.0
ember-data: 2.3.3
fastboot: 0.3.4

**Comment by tomdale** [comment]
@speed1speed1 Can you try with Ember Data 2.4 beta and let me know if that fixes the issue?

**Comment by speed1speed1** [comment]
ember: 2.3.0
ember-data: 2.4.0-beta.2
fastboot: 0.3.4

Cool.
This fixed the ajax issue, but next issue is adapter headers not working.
Fastboot is only support ember-data for now right?
Support jquery in general seem to be difficult.

**Comment by acorncom** [comment]
@speed1speed1 additional details on jQuery support here: https://github.com/tildeio/ember-cli-fastboot/issues/101

**Comment by tomdale** [comment]
I think we can close this. @speed1speed1, please open a new issue if you hit additional problems.
