### ISSUE TITLE
Add ability to strip out <script> tags

### ISSUE THREAD

**Issue by RuslanZavacky** [tildeio/ember-cli-fastboot#108]
Google bot (and probably others) when render page with javascript, will load all script tags and will wait for page to load. And as experiment shows will wait not more than 5 seconds.

So when we build HTML output and leave script tags, Google will still wait for Ember app to boot.

My idea is to add a config option for fastboot to enable/disable automatically stripping tags when serving output.

**Comment by tomdale** [comment]
@RuslanZavacky I am definitely open to having an option for this. Probably belongs on the `FastBootServer` in https://github.com/ember-fastboot/ember-fastboot-server.
