### ISSUE TITLE
"ReferenceError: self is not defined" on "embr fastboot"

### ISSUE THREAD

**Issue by LukeLaupheimer** [tildeio/ember-cli-fastboot#12]
Here's what I get when I try to run `ember fastboot`. To the best of my knowledge, everything is installed correctly, but apparently not.

```bash
elp2:example_project user$ ember fastboot
version: 0.2.2
Built project successfully. Stored in "dist".
self is not defined
ReferenceError: self is not defined
    at <anonymous>:63785:35
    at <anonymous>:75317:4
```

This is in a completely clean project that was created using `ember new`.

Any ideas?

**Comment by tomdale** [comment]
What version of Ember?

**Comment by LukeLaupheimer** [comment]
Well, I get this for the Ember CLI:
```bash
elp2:example_project user$ ember --version
version: 0.2.2
node: 0.12.1
npm: 2.7.4
elp2:example_project user$
```

And this is the version of Ember I'm using:
```js
/*!
..
 * @version   1.13.0-beta.1+canary.57f1fa1b
...
*/
```

Hope that helps.

**Comment by tomdale** [comment]
@LukeLaupheimer Is this the same error as #11? If so, looks like an issue with Ember Data. I'll investigate.

**Comment by patricksimpson** [comment]
@tomdale @LukeLaupheimer I have a PR to ember data...

**Comment by rwjblue** [comment]
Fixed upstream.  Ember Data canary builds should be working properly now.
