### ISSUE TITLE
Fastboot issues

### ISSUE THREAD

**Issue by Globegitter** [tildeio/ember-cli-fastboot#2]
Not sure if this is the place to report bugs but just tired out `ember-cli-fasboot` and not seem to be getting it to work.

When I install the latest `0.0.2` I get the following error:
```
version: 0.2.0-beta.1
Built project successfully. Stored in "dist".
DEBUG: -------------------------------
DEBUG: Ember      : 1.12.0-beta.1+canary.f5873415
DEBUG: Ember Data : 1.0.0-beta.15
DEBUG: -------------------------------
Ember FastBoot running at http://:::3000

undefined:0
/* jshint ignore:start */

TypeError: Cannot read property 'entries' of undefined
    at <anonymous>:58848:38
    at Array.exports.default.mixin.Mixin.create.find (<anonymous>:38120:30)
    at Ember.DefaultResolver.extend.findModuleName (<anonymous>:58847:44)
    at resolveOther (<anonymous>:58712:37)
    at superWrapper (<anonymous>:26855:20)
    at exports.default.EmberObject.default.extend.resolveView (<anonymous>:14407:19)
    at exports.default.EmberObject.default.extend.resolve (<anonymous>:14267:43)
    at Object.resolve [as resolver] (<anonymous>:14033:23)
    at resolve (<anonymous>:11558:29)
    at Object.Registry.resolve (<anonymous>:11102:21)
```

After installing straight from master, all works fine and I get `Ember FastBoot running at http://:::3000` but when I go to `http://localhost:3000/` it just times out and nothing logs. 

This is a very barebone app just with a an application and index template using the pod structure, running on the latest `iojs`, `ember`, `ember-cli`, etc.

**Comment by tomdale** [comment]
@Globegitter Hey, can you try now with 0.0.4? I fixed a few issues on Ember master that caused regressions.

**Comment by gdub22** [comment]
I'm experiencing a similar problem:
The fastboot server successfully starts running:  `Ember FastBoot running at http://:::3000` 
Then when trying to open `http://localhost:3000/`, it just hangs forever. No output in the console.
Current setup:
```
ember-cli-fastboot: 0.0.4
ember-cli: 0.2.0
ember: 1.12.0-beta.1+canary.a6fdd051
```
It does work fine with a new, blank ember-cli app.  I've dumbed down a complex app to at least get the fastboot server running. With some quick, crude debugging I think it's hanging at the `App.visit` promise.  Any pointers on what could cause it to hang, or help with debugging in general? @tomdale

**Comment by tomdale** [comment]
@gdub22 I'm going to try to write up a guide on how to debug a failing app in FastBoot mode this weekend. It's actually pretty nice once you get it up and running (and doesn't segfault anymore after the latest node-inspector release, yay!) but it's non-obvious to set it up.

**Comment by tomdale** [comment]
@gdub22: https://github.com/tildeio/ember-cli-fastboot#troubleshooting

Let me know if this is helpful.

**Comment by gdub22** [comment]
@tomdale :+1: yes, thanks!

**Comment by tomdale** [comment]
Gonna close this for now, please file a new issue with any problems you hit!
