### ISSUE TITLE
Enable route pre-rendering / cacheing via fastboot mechanisms.

### ISSUE THREAD

**Issue by runspired** [tildeio/ember-cli-fastboot#21]
I've hit many use cases on mobile where optimized routes will still have rendering times > 100ms.  Sometimes these routes, such as index route, are heavily trafficked by a single user, being entered and left often.

I've tried various non-ember centric methods of pre-rendering and cacheing views and their html, but these approaches' reliance on private APIs inevitably leaves them heavily susceptible to internal api churn.

It would be a huge benefit for apps that need to highly optimize rendering if the fastboot work resulted in additional hooks for connecting and disconnecting rendered html to any view, but especially the primary view/component for a route.

Something such as `.on('viewWillDisconnect')` which could receive the current state and DOM for a view and `.on('viewWillConnect')` which could be provided a state and a DOM that's either been cached previously or pre-rendered via an ajax call to the server running fastboot.  The ultimate goal being that rendering could be optimally balanced between client and server as needed.

It's possible this is already part of the plan for Fastboot, but I haven't seen this particular use case of feature set discussed.  If it is part of the plan, I'd love to read more about it.

**Comment by jimmyjamieson** [comment]
I was wondering about caching myself. If you had 1000 users all hitting a route at once, you don't want the node server rendering 1000 requests, but passing a static cached version. Is that how it will work?

Sorry, I'm hijacking a little.

**Comment by runspired** [comment]
@jimmyjamieson I'm referring to "fastbooting" and pre-rendering routes AFTER the app has already booted, sometimes that's desired.

As for your idea, you're going to have that problem no matter what if it's behind a login and user specific data.  I don't know if this is on their radar, but being able to specify whether a route is user/session specific or not would go a long way to allowing that request to cache.

**Comment by tomdale** [comment]
Interesting idea but I think it's out of scope for FastBoot 1.0. Let's revisit this again once we ship rehydration, as that's still the largest unknown.
