### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by furley** [tildeio/ember-cli-fastboot#24]
When I start Fastboot I'm getting this nondescript error. Is this an issue with Canary?

```
$ ember fastboot
version: 0.2.3
Built project successfully. Stored in "dist".
self is not defined
ReferenceError: self is not defined
    at <anonymous>:60862:35
    at <anonymous>:72394:4
```

**Comment by furley** [comment]
More info: 
```
$ ember --version
version: 0.2.3
node: 0.12.2
npm: 2.7.6
```

**Comment by stefanpenner** [comment]
You have an old version of ember data

**Comment by furley** [comment]
I have 1.0.0-beta.16.1. That seems to be the latest version.

**Comment by rwjblue** [comment]
@furley - You have to use canary version of Ember Data.

**Comment by rwjblue** [comment]
The underlying issue was fixed in https://github.com/emberjs/data/pull/2954 which was drummed up by #11.

**Comment by rwjblue** [comment]
I'm going to close this, as it has been fixed upstream.  Sorry for the troubles, let us know if updating to canary doesn't fix the issue!

**Comment by furley** [comment]
I'm pretty sure I have the most up to date canary as well, but will just stop trying.

**Comment by rwjblue** [comment]
@furley - I am referring to canary version of Ember Data.  Specifically, you need a build that includes the changes from https://github.com/emberjs/data/pull/2954.

**Comment by furley** [comment]
Ahh I see now. I still haven't successfully run fastboot, but I'm making more progress. Thanks for the help.
