### ISSUE TITLE
Middleware hook?

### ISSUE THREAD

**Issue by trabus** [tildeio/ember-cli-fastboot#3]
Are you intending on providing a middleware hook similar to [this](https://github.com/ember-cli/ember-cli/blob/master/lib/tasks/server/express-server.js#L72)? Our app has some processing and additions to the page that need to happen before the page is served.

**Comment by tomdale** [comment]
@trabus Hey Jake, good talking to you at EmberConf about this.

As of https://github.com/tildeio/ember-cli-fastboot/commit/d3f9dda813d5bb6bbbbcfa47cdbbbaa7f59564d4 I've started refactoring the internals to just be an Express middleware. Let me know if this helps with your use case. If not, I'd love to work with you to find something that does.

**Comment by trabus** [comment]
@tomdale Thanks!

I'll be sure to update with any issues once we've been able to try it out!
