### ISSUE TITLE
Issue when starting project initially

### ISSUE THREAD

**Issue by code0100fun** [tildeio/ember-cli-fastboot#30]
Issue pertains to a reference to self that is not defined:

![](http://i.imgur.com/f6V7NkQ.png)

**Comment by rwjblue** [comment]
Dupe of https://github.com/tildeio/ember-cli-fastboot/issues/11, https://github.com/tildeio/ember-cli-fastboot/issues/12, and https://github.com/tildeio/ember-cli-fastboot/issues/24.

The error is with Ember Data version.  You must use canary Ember Data (if you need Ember Data).
