### ISSUE TITLE
Brand new ember-cli app results in "Could not read config from meta tag with name"

### ISSUE THREAD

**Issue by ianpetzer** [tildeio/ember-cli-fastboot#42]
Hi,

I create a new ember-cli app today and added the ember-cli-fastboot addon.

I'm running against ember canary as of today (#678e59e1cd), however when I try to run 'ember fastboot' I get the error below.

 Any help would be greatly appreciated.

    $ ember fastboot --serve-assets
    version: 0.2.6
    The option '--serve-assets' is not registered with the fastboot command. Run `ember fastboot --help` for a list of supported options.
    Built project successfully. Stored in "dist".
    Could not read config from meta tag with name "try/config/environment".
    Error: Could not read config from meta tag with name "try/config/environment".

My index.html is the default generated one.

Thanks,
Ian

**Comment by rwjblue** [comment]
`--serve-assets` is only on master (hasn't been published to NPM in a version yet).

**Comment by ianpetzer** [comment]
Oh right.

Running against HEAD perfectly. 

Thanks
