### ISSUE TITLE
Error: no global: `self` or `global` found

### ISSUE THREAD

**Issue by atsjj** [tildeio/ember-cli-fastboot#47]
#45

```
version: 0.2.7
no global: `self` or `global` found
Error: no global: `self` or `global` found
    at <anonymous>:11348:11
    at internalRequire (<anonymous>:10631:16)
    at internalRequire (<anonymous>:10627:24)
    at internalRequire (<anonymous>:10627:24)
    at internalRequire (<anonymous>:10627:24)
    at internalRequire (<anonymous>:10627:24)
    at internalRequire (<anonymous>:10627:24)
    at internalRequire (<anonymous>:10627:24)
    at requireModule (<anonymous>:10597:14)
    at <anonymous>:67551:1
```

Bower config set to use Ember and Ember Data canary.

The module throwing the error is `backburner/platform`.

**Comment by harianus** [comment]
Having the same issue here

```
$ ember fastboot --environment production
version: 0.2.7
Built project successfully. Stored in "dist".
no global: `self` or `global` found
Error: no global: `self` or `global` found
    at <anonymous>:4:10858
    at a (<anonymous>:4:3121)
    at a (<anonymous>:4:3096)
    at a (<anonymous>:4:3096)
    at a (<anonymous>:4:3096)
    at a (<anonymous>:4:3096)
    at a (<anonymous>:4:3096)
    at a (<anonymous>:4:3096)
    at t (<anonymous>:4:3648)
    at <anonymous>:19:24691
```

**Comment by tomasbasham** [comment]
I am getting the same issue too with `2.0.0-canary+e2355a6c`

**Comment by jamesmenera** [comment]
Hey any workaround for this?

**Comment by tomdale** [comment]
Hmm, looks like a regression in Ember. I'll try to take a look at this soon. Sorry for the trouble!

**Comment by rwjblue** [comment]
I think it would be odd to be an Ember regression, as we have some node-tests that confirm an app can boot and some rudimentary things can be rendered via simple-dom.  I would suspect one of our deps is doing something funky...

**Comment by atsjj** [comment]
@rwjblue if I followed the lines in stack trace correctly, I ended up in one of the backburner modules. Sorry, I thought I had pasted that.

**Comment by tomdale** [comment]
@rwjblue Indeed. If it is backburner, I'm surprised the Ember node tests aren't catching it.

**Comment by rwjblue** [comment]
Very bizarre indeed. Either something is wrong and those tests are not running properly, or they do not exercise whatever is triggering this error.

**Comment by ofbriggs** [comment]
I submitted PR #48 to fix this, I ran into additional errors but those were fixed by using master instead of the published npm version. Any plans to publish a new version soon?
