### ISSUE TITLE
indexOf of undefined while booting

### ISSUE THREAD

**Issue by harianus** [tildeio/ember-cli-fastboot#50]
When including the current master version (https://github.com/tildeio/ember-cli-fastboot/commit/8ab0b33ca08c6cd48f597646e5fe09ef8c09a1dc) of fastboot like this

```
// package.json
{
  ...
  "devDependencies": {
    "ember-cli-fastboot": "tildeio/ember-cli-fastboot.git#master",
    ...
  }
}
```

And then just run `npm intall` and `ember fastboot`, I get this error

```
version: 0.2.7
Built project successfully. Stored in "fastboot-dist".
Cannot read property 'indexOf' of undefined
TypeError: Cannot read property 'indexOf' of undefined
    at <anonymous>:19:3258
    at <anonymous>:21:15567
```

Using `ember#canary`

**Comment by kratiahuja** [comment]
+1 seeing the same error after manually applying #48 patch.

**Comment by kratiahuja** [comment]
This doesn't seem to be arising due to #48. It is coming from ember-data since Ember.EnumerableUtils got deprecated. 

Using the canary version of ember-data fixed the issue.

**Comment by harianus** [comment]
I didn't use ember data at all

**Comment by victor-stone** [comment]
fwiw I got things to work by removing ember-data from devDendencies

Then I ran into #52 and commented out that line (though I need ajax!)

**Comment by kratiahuja** [comment]
If you bump version of ember-data to canary, it should work for you. You would need to update bower.json to use canary version of ember-data.

**Comment by tomdale** [comment]
This should be fixed in latest Ember Data. Please reopen if you're still having issues.
