### ISSUE TITLE
Exception: TypeError in ajax.js

### ISSUE THREAD

**Issue by victor-stone** [tildeio/ember-cli-fastboot#52]
Shortly after boot with the lastest build:

> undefined: [74](https://github.com/tildeio/ember-cli-fastboot/blob/master/app/initializers/ajax.js#L33)
>       registry.injection('adapter', 'ajax', 'ajax:node');
>                   ^
> TypeError: undefined is not a function

This is in app/initializers/ajax.js

**Comment by timkendall** [comment]
+1 *(Had to pull directly from master to fix [#47](https://github.com/tildeio/ember-cli-fastboot/issues/47))*
