### ISSUE TITLE
URL search/query params dropped before routing

### ISSUE THREAD

**Issue by victor-stone** [tildeio/ember-cli-fastboot#53]
When hitting the server with an url with query params [this line](https://github.com/tildeio/ember-cli-fastboot/blob/master/lib/models/server.js#L57) drops the search part of the url and it is never picked up because the Location is forced to 'none' [here in Ember](https://github.com/emberjs/ember.js/blob/1d7b833664292bc6644adc41a7dd9a842ea078c5/packages/ember-application/lib/system/application.js#L715)

**Comment by victor-stone** [comment]
More info: Even if I hack the FB server to use req.url (instead of [req.path](https://github.com/tildeio/ember-cli-fastboot/blob/master/lib/models/server.js#L57)) then [this transition abort()](https://github.com/tildeio/router.js/blob/master/lib/router/router.js#L59) in the underlying router lib forces an HTTP Status 500

To recreate:
> curl http://localhost:3000/somepath?foo=bar

**Comment by tomdale** [comment]
Thanks, I'll look into this.

**Comment by scottmessinger** [comment]
I can confirm this bug. Anything I can do to help fix it?

**Comment by chancancode** [comment]
the transition bug should be fixed on canary, but fastboot needs to be updated to consume the new API; I'll send a PR this weekend!

**Comment by victor-stone** [comment]
this is great news (!) - any updates?

**Comment by tomdale** [comment]
@chancancode Any update on this?

**Comment by chancancode** [comment]
If I am reading myself correctly, it should be fixed now?

**Comment by chancancode** [comment]
I see. I was referring to the "redirect bug", which is indeed fixed in ember now. I think the line @victor-stone was pointing to (https://github.com/ember-fastboot/ember-fastboot-server/blob/5b89456cee90d10785978e2736742a2f1ce7fda7/lib/server.js#L69) still needs to be changed to use `req.url`?
