### ISSUE TITLE
TypeError: Object #<Object> has no method 'inject'

### ISSUE THREAD

**Issue by zion03** [tildeio/ember-cli-fastboot#65]
I trying to run fastboot but get error:
DEBUG: -------------------------------
DEBUG: Ember      : 1.13.2
DEBUG: Ember Data : 1.0.0-beta.16.1
DEBUG: -------------------------------
[ ] -view-registry:main ........................................ chat/main/-view-registry
[ ] -view-registry:main ........................................ undefined
[ ] -view-registry:main ........................................ chat/-view-registry
[ ] -view-registry:main ........................................ chat/-view-registrys/main
[ ] -view-registry:main ........................................ undefined
[ ] -view-registry:main ........................................ chat/main/-view-registry
[ ] -view-registry:main ........................................ undefined
[ ] -view-registry:main ........................................ chat/-view-registry
[ ] -view-registry:main ........................................ chat/-view-registrys/main
[ ] -view-registry:main ........................................ undefined
Ember FastBoot running at http://0.0.0.0:8089

undefined:1500
        application.inject('adapter', 'ajax', 'ajax:node');
                    ^
TypeError: Object #<Object> has no method 'inject'
    at Object.exports.default.initialize (<anonymous>:1500:21)
    at <anonymous>:17882:23
    at <anonymous>:17909:9
    at visit (<anonymous>:15794:5)
    at DAG.topsort (<anonymous>:15905:9)
    at _emberRuntimeSystemNamespace.default.extend._runInitializer (<anonymous>:17908:13)
    at _emberRuntimeSystemNamespace.default.extend.runInitializers (<anonymous>:17878:12)
    at _emberRuntimeSystemNamespace.default.extend.boot (<anonymous>:17795:12)
    at _emberRuntimeSystemNamespace.default.extend.domReady (<anonymous>:17781:12)
    at Queue.invoke (<anonymous>:14456:16)

**Comment by rwjblue** [comment]
ember-cli-fastboot is not compatible with 1.13.  You must use it with canary builds.  The steps are listed in https://github.com/tildeio/ember-cli-fastboot#installation.

**Comment by tomdale** [comment]
@rwjblue is correct that we require canary for the time being. This is because FastBoot relies on the `visit()` feature flag which is still off by default. I'm hoping this will be enabled by default in a release in the very near future.
