### ISSUE TITLE
backburner calls setTimeout() on server fetch

### ISSUE THREAD

**Issue by victor-stone** [tildeio/ember-cli-fastboot#67]
It doesn't always happen but on certain cases where there's lots of ajax and queued activity backburner will call (window.)setTimeout() causing the app to crash and not return a page. My workaround was to detect the server and [stub out the call](https://github.com/ArtisTechMedia/dig.ccMixter/blob/fastboot/app/app.js#L14) which is a shaky solution (works for me) but hardly ideal.

**Comment by rwjblue** [comment]
Can you provide a repo that we can use to reproduce this?

**Comment by victor-stone** [comment]
I'm trying - the app has grown a bit but I can confirm it happens every time I make an (n)ajax call of any substance [like this one](http://ccmixter.org/api/query?tags=&dataview=links_by&limit=10&sort=rank&ord=desc&oneof=remix,extended_mix&f=json&search_type=all&lic=all) and then 'curl' to the localhost. Hope that helps but I will try to get a test harness up too.

**Comment by stefanpenner** [comment]
you have hit an auto-run.

**Comment by victor-stone** [comment]
that is very likely because I can't repo it using just ajax and promises. I thought I had dodged all the scheduling code under FB but I'll just have to whittle down the app until it stops doing it.

**Comment by tomdale** [comment]
`setTimeout` and `clearTimeout` should both be exposed now
