### ISSUE TITLE
JSONAPIAdapter does not support `ajaxError`

### ISSUE THREAD

**Issue by danmcclain** [tildeio/ember-cli-fastboot#89]
I assume the same for `ajaxSuccess`, but here is the line in question: https://github.com/tildeio/ember-cli-fastboot/blob/master/app/initializers/server/ajax.js#L14

When the API returns an error, fastboot dies

**Comment by rwjblue** [comment]
`ajaxError` and `ajaxSuccess` were removed in Ember Data in favor of `handleResponse`, seems like this is left over?

**Comment by tomdale** [comment]
@danmcclain We can close this now, right?

**Comment by danmcclain** [comment]
Yes
