### ISSUE TITLE
AJAX request from fastboot do not have correct headers

### ISSUE THREAD

**Issue by danmcclain** [tildeio/ember-cli-fastboot#90]
Somewhat related to: https://github.com/tildeio/ember-cli-fastboot/issues/89

Our API follows the JSONAPI spec, and requires the `application/vnd.json+api` content-type/accepts header. Even though it is specified via JSONAPIAdapter, the "ajax" requests coming from fastboot lack that header

**Comment by tomdale** [comment]
@danmcclain This was a najax bug, can you try with the updated release which bumps the version?

**Comment by danmcclain** [comment]
@tomdale Didn't work with fastboot 0.2.0 with najax 0.3.2, since `JSONAPIAdapter` uses `jqXHR.beforeSend`. I have a pull request on najax: https://github.com/najaxjs/najax/pull/25

**Comment by danmcclain** [comment]
This is where `beforeSend` is used: https://github.com/emberjs/data/blob/v2.3.2/addon/adapters/json-api.js#L32-L38

**Comment by speed1speed1** [comment]
I also got the "adapter.ajaxError" error.
Used RESTAdapter at same line in https://github.com/tildeio/ember-cli-fastboot/blob/master/app/initializers/server/ajax.js#L14
But not broken in response, it broken at call.
This problem has been resolved yet?

**Comment by danmcclain** [comment]
@speed1speed1 Najax needs a new release first, the PR has been accepted there

**Comment by tomdale** [comment]
Gonna close this because the imminent PR fixes it.
