### ISSUE TITLE
Dockerized FastBoot Server

### ISSUE THREAD

**Issue by tomdale** [tildeio/ember-cli-fastboot#99]
One of our goals for FastBoot is to make it _really_ easy to install and deploy.

To that end, I'd love it if someone adapted the [Elastic Beanstalk FastBoot server](https://github.com/tomdale/ember-fastboot-elastic-beanstalk) for Docker. I have to confess I've never used Docker before, so while I'm happy to do it, it would be much faster for someone who does have some experience to tackle it.

**Comment by jpadilla** [comment]
@tomdale I'd love to work on this. Fork and PR to https://github.com/tomdale/ember-fastboot-elastic-beanstalk ?

**Comment by tomdale** [comment]
@jpadilla Awesome! Probably separate repo—will leave the EB one as is for the moment. Happy to have the repo under your user on GitHub.

**Comment by jpadilla** [comment]
First go at this https://github.com/jpadilla/ember-fastboot-docker

Usage:

```
$ docker run \
  --rm -it \
  -p 8080:3000 \
  -v $(pwd)/fastboot-dist:/src/fastboot-dist \
  jpadilla/ember-fastboot-server
```

I'm currently working on improving overall image size a bit more.

Thoughts/feedback?

**Comment by tomdale** [comment]
@jpadilla Looks great. Let's track development in that repo.

**Comment by arjansingh** [comment]
Shameless plug: https://github.com/dollarshaveclub/fastboot-docker

**Comment by flecno** [comment]
Both repos are not maintained anymore. Is there any other docker image to for fastboot?

**Comment by arjansingh** [comment]
@flecno If you just need a static file server, I would just use [Alpine Node](https://github.com/mhart/alpine-node) or [Nginx](https://hub.docker.com/_/nginx/) bases images and build your artifacts on those.

Building an app is only [this part](https://github.com/dollarshaveclub/fastboot-docker/blob/master/Dockerfile#L55-L109) of the Docker file. You can pretty much copy/paste/modify that part and it will work. If you have private repositories in your `package.json`, also look at the SSH cert section above those lines.

Hope that helps.
